[project]
name = "meu-ola"
version = "0.1.4"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "click>=8.3.0",
    "rich>=13.0.0",
    "pyfiglet>=0.8.0",
]

[project.scripts]
ola = "main:cumprimentar"
